# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Salih KARAHAN
tagline:          'A Jekyll theme'
description:      'Software Developer'
url:              http://salihkarahan.github.io

author:
  name:           'Salih KARAHAN'
  url:            '#twitter'

paginate:         5

# Custom vars
version:          2.0.0

github:           https://github.com/SalihKARAHAN
  repo:           https://github.com/SalihKARAHAN
